[package]
name = "wasm-env-minimal-example"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "5.0"
wasmtime-wasi = "5.0"
anyhow = "1.0.68"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "net"] }
